# Generated by Django 4.0.4 on 2022-05-31 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_diary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='iflock',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='diary',
            name='ifpublic',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='diary',
            name='ifremind',
            field=models.IntegerField(),
        ),
    ]
