# Generated by Django 4.0.4 on 2022-05-31 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_diary_iflock_alter_diary_ifpublic_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Diary',
        ),
    ]
