# Generated by Django 4.0.4 on 2022-05-31 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_delete_diary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('diaryid', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=2000)),
                ('ifpublic', models.IntegerField()),
                ('iflock', models.IntegerField()),
                ('ifremind', models.IntegerField()),
            ],
        ),
    ]
