# Generated by Django 4.0.4 on 2022-06-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_alter_diary_iflock_alter_diary_ifpublic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='iflock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='diary',
            name='ifpublic',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='diary',
            name='ifremind',
            field=models.IntegerField(default=0),
        ),
    ]
