# Generated by Django 4.0.4 on 2022-06-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_diaryreminddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('personid', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
    ]
