# Generated by Django 4.0.4 on 2022-06-07 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_personel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Personel',
        ),
    ]
