# Generated by Django 4.0.4 on 2022-06-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_delete_personel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('personid', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('personname', models.CharField(max_length=200)),
                ('personsign', models.CharField(max_length=200)),
                ('follownum', models.IntegerField(default=0)),
                ('fansnum', models.IntegerField(default=0)),
                ('commentnum', models.IntegerField(default=0)),
                ('likenum', models.IntegerField(default=0)),
            ],
        ),
    ]
