# Generated by Django 4.0.4 on 2022-06-07 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_likelist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikeList',
        ),
    ]
