# Generated by Django 4.0.4 on 2022-06-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_delete_likelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diaryid', models.CharField(max_length=200)),
                ('personid1', models.CharField(max_length=200)),
                ('personid2', models.CharField(max_length=200)),
                ('liketime', models.CharField(max_length=200)),
            ],
        ),
    ]
