# Generated by Django 4.0.4 on 2022-06-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_commentlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personid1', models.CharField(max_length=200)),
                ('personid2', models.CharField(max_length=200)),
                ('followtime', models.CharField(max_length=200)),
            ],
        ),
    ]
