# Generated by Django 4.0.4 on 2022-05-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('username', models.CharField(max_length=30)),
                ('passwd', models.CharField(max_length=50)),
                ('userid', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
