# Generated by Django 4.0.4 on 2022-05-28 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_person_delete_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='User',
        ),
    ]
