# Generated by Django 4.0.4 on 2022-05-31 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_rename_person_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('diaryid', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=2000)),
                ('ifpublic', models.IntegerField(max_length=1)),
                ('iflock', models.IntegerField(max_length=1)),
                ('ifremind', models.IntegerField(max_length=1)),
            ],
        ),
    ]
