# Generated by Django 4.0.4 on 2022-06-04 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_diarylock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiaryLock',
        ),
    ]
